name: Test

on:
  pull_request:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
  push:
    branches:
      - master
      - main
#     - devel
#     - develop
#     - development

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Checkout
        uses: actions/checkout@main
      - name: BUILD
        uses: judahh/nodeBuild@main
        with:
          node_version: ${{ matrix.node-version }}
      - name: TEST
        uses: judahh/yarnTest@main
      - name: ZIP TO ARTIFACT
        if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
        uses: judahh/zipToArtifact@main
        with:
          production: true
